### ISSUE TITLE
Lost Snippets

### ISSUE THREAD

**Issue by AaronKnowls** [rabirabirara/obsidian-jelly-snippets#10]
I lost all my snippets after last plugin update :(

I guess there is no way to restore them back, is it?

In any case, thank you for this great and useful plugin.

**Comment by kikijiki** [comment]
The snippets are still there if you open your `.obsidian/plugins/jelly-snippets/data.json`.

You can rename `searchSnippetsFile` to `snippetsFile` to restore them (while Obsidian is closed).
