### ISSUE TITLE
Replacements with spaces?

### ISSUE THREAD

**Issue by jeff-h** [rabirabirara/obsidian-jelly-snippets#12]
I am wondering if this plugin would work for the following snippet. I would like to replace the following key sequence:

<kbd>space</kbd> <kbd>x</kbd> <kbd>space</kbd>

with the following:

<kbd>space</kbd> <kbd>×</kbd> <kbd>space</kbd>

(ie replace the lowercase `x` with the multiplication symbol `×`)

I have defined my snippets like so:

```
Snip me! |+| Snippet successfully replaced.
-==-
 x |+|  ×
```

However, no matter what combination of double-spaces etc I have tried, I cannot get it to both achieve what I describe above, and also not trigger when typing something such as `fox and`.

**Comment by rabirabirara** [comment]
Well, there is a simple answer to that, and that's because I'm trimming the snippets to get rid of the newlines in the settings file. Luckily, I don't need to do that. Fixing right now.

**Comment by rabirabirara** [comment]
It's in main.  a4c6600aaf9bd9b9f91b5dbec82b0d2ec69397bb

As for releasing it, I have a few other features I want to add too, so I might postpone the release until I've added those... if you need this feature right now, you can:

1. Copy `main.ts` and use `npm` (or some alternative) to compile the Typescript yourself in your .obsidian plugin repo.
2. Ask me to send you the modified `main.js` file, and you simply put that in your plugin repo.

**Comment by jeff-h** [comment]
Thanks @rabirabirara! I'm happy to wait for the next release, but it's great to know there's a fix coming :)

**Comment by rabirabirara** [comment]
Okay, so a MUCH better fix has come in. Unfortunately, you now need to use symbols in your snippets to add whitespace, but I think this is much better than what I did before which was hacky and broken.

7e1c6f7954a982ee1e2ca7ba197e4484c3b5ada9

I will be releasing this update very soon.

**Comment by jeff-h** [comment]
Sounds great! I look forward to trying it out.

**Comment by jeff-h** [comment]
I'm a bit confused how to use the new functionality. I tried this replacement:

`%\sx%\s |+| %\s×%\s`

but it doesn't trigger. I was hoping it would look for space-x-space and replace that with space-multiplicationsymbol-space.

**Comment by rabirabirara** [comment]
1. This brought my attention to a bug in that I am trimming all left whitespace for the left-hand sides of snippets. A quick hack is coming tomorrow.
2. The symbols are only for the RHS of snippets; everything on the LHS is pure text and *exactly* what the plugin searches for. This does mean, in combination with the above, that you have to have 1 newline between individual snippets, right after the snippet divider. (Doesn't really change a thing, I suppose.)

Once I publish the bugfix, you can put the following in your file:

```
...
-==-
 x  |+| %\s×%\s
```
..using periods to visualize the spaces:
```
.x..|+|.%\s×%\s
```

Sans fix, the closest you can get is:
```
x  |+| %\s×%\s
```
..where there's an extra space between `x` and `|+|`. This doesn't include the space left of `x`.

**Comment by rabirabirara** [comment]
eba93321df5396458435fafdb6d219a35b2b8db5 should fix this entirely. Closing. Will update the README to make more sense in the near future.

**Comment by jeff-h** [comment]
It works! Thanks so much :)
