### ISSUE TITLE
Allow change cursor position via snippet

### ISSUE THREAD

**Issue by nirtamir2** [rabirabirara/obsidian-jelly-snippets#14]
Hi!
I came to this plugin because the text-generator plugin did not work for me, and I looked at this issue https://github.com/ArianaKhit/text-snippets-obsidian/issues/67 so I gave it a try.
It works! I can IMO that it's not that easy to create the snippets (because the separator conventions you chose) but they can be configured so it's ok.
I created a snippet
```
kbd |+| <kbd></kbd>
-==-
```
When I write `kbd` and click tab it will open that like [emmet](https://emmet.io/) style.
It works. But now I want to change the cursor position to be inside the `kbd` element.
Can we tweak the cursor position?
The existing text-generator supports such syntax (via `$end$`). It reminds me of Jetbrains IDE live template - which is super powerful.
Thanks!

**Comment by rabirabirara** [comment]
This is actually already on the feature list!

Now that someone has actually asked for it, I suppose I'd better get to it. (Been a bit busy with my job and all.)

**Comment by liluzhang** [comment]
both of them plugin did not work for me,but I find the way.
so Maybe you can try latex suite：https://github.com/artisticat1/obsidian-latex-suite#snippets
https://github.com/artisticat1/obsidian-latex-suite/discussions/50
your requirement can be rewrited:  {trigger: "kbd", replacement: "<kbd>\n$0\n</kbd>", options: "tA"},   
Don't add space after"\n".

**Comment by rabirabirara** [comment]
Yes, that is a great plugin. I don't use it myself but I'm sure it has the functionality you need.

**Comment by j-milkovits** [comment]
Hey there, 
I second the request for this feature, it would be a great addition to the plugin!
As all the other pure text-snippet plugins seem to be outdated, your plugin seems to be the only one :D 
If you ever need any help, I can also give it a try if I find the time for it.:)

**Comment by rabirabirara** [comment]
6b6787a552f9a34969c05f902add7009a3ce2785

With this series of commits I've added this capability. I'll make a writeup on how to use the feature.

For now, the syntax I put in is: `%\x` where `x` is the symbol. There are 3 whitespace symbols (n, t, s) and 1 functionality symbol: `e`, which is the one you want. In other words:

`replace |+| left%\eright`

Trigger this, and you'll end up with:

`left|right`

Where '|' represents your cursor, of course.

https://github.com/rabirabirara/obsidian-jelly-snippets/issues/14#issuecomment-1732394148

Thanks for the offer! This whole program is open-source anyway, so if you wanted to mess around with it go right ahead. It's fine if you don't feel the need; the program isn't too difficult to maintain anyway. I just have to get around to things, and perhaps develop unit tests. (Definitely that, actually.)
