### ISSUE TITLE
Selects back to indent after checkbox

### ISSUE THREAD

**Issue by gbwellman** [rabirabirara/obsidian-jelly-snippets#17]
First up, I'm loving this plugin!

However, I've been noticing that when this plugin is enabled, pressing space/return after a check box eg. 
' - [ ] TodoItem'
ends up selecting all the text up to the indent. As below: 

![image](https://github.com/rabirabirara/obsidian-jelly-snippets/assets/7187340/ad466dc4-ac77-4a6f-815e-fa2ac6b19d0d)
 
Perhaps something is conflicting in 'live preview' editing mode since it works perfectly in 'source mode'? 

Is anyone else having this problem?

**Comment by rabirabirara** [comment]
I can reproduce the problem. Yes, the behavior is extremely broken in Live Preview. I'll look into it.

**Comment by rabirabirara** [comment]
2e1764a3bf486929c97f6a7a24a9cab4f0055de4 should fix this. Reopen and let me know if you have a problem.

Thank you for using the plugin!
