### ISSUE TITLE
Option for new lines

### ISSUE THREAD

**Issue by ltrook21** [rabirabirara/obsidian-jelly-snippets#7]
Would love to see an option to add new lines to the snippets. Thanks for all of your hard work!

**Comment by rabirabirara** [comment]
Yes - to be specific, do you mean to support new lines in the left hand side of a snippet? Or to be able to specify newlines with a control character?

I will *hopefully* get on it (either one) in a few weeks or so (graduation is coming up and I've got the busiest classes of my degree cluttering my desk).

**Comment by rabirabirara** [comment]
Ok. After the busiest summer of my life, and a month without internet, I have finally rewritten the bloody thing. You can now put newlines in any part of the snippet, LHS or RHS. Closed! Reopen if you see any problems.
