### ISSUE TITLE
Enable setting the snippet divider to a newline character (\n)

### ISSUE THREAD

**Issue by KosmosisDire** [rabirabirara/obsidian-jelly-snippets#8]
I never use multiline snippets and so for me it would be much cleaner to use a new line to seperate each snippet. I would expect to be able to enter "\n" into the `snippet line divider` box to acheive this.

Thanks for the plugin! I switched from Text Snippets because it no longer worked.

**Comment by rabirabirara** [comment]
With that in and a new tag published, I'll close this.

Please drop a comment if I broke anything.
